#%RAML 0.8

title: Lagash
version: 1
baseUri: http://localhost:5570/
mediaType: application/json

/:
  description: Servicios basicosdel sistema
  get:
    description: Retorna el tiempo de actividad de los servicios
    body:
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "version": "0.0.0",
                "uptime": "2018-03-13T20:45:57.3229933-04:00"
              }

/v1:
  description: Servicios de autenticación del sistema
  /login:
    post:
      description: Crea un nueva session para un usuario
      body:
        application/json:
          schema: !include schema/login/data.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/login/response.json
  /logout:
    post:
      description: Cierra la session de usuario
      responses:
        200:

/v1/users:
  description: Servicios de creacion, edicion y eliminacion de usuarios
  post:
    description: Crea un nuevo usuario
    body:
      application/json:
        schema: !include schema/user/user.post.json
    responses:
      200:
        body:
          application/json:
            schema: !include schema/user/user.json
  get:
    description: Recuperar todos los usuarios
    responses:
      200:
        body:
          application/json:
            schema: !include schema/user/user.array.json

  /{user_id}:
    get:
      description: Recuperar un usuario especifico
      responses:
        200:
          body:
            application/json:
              schema: !include schema/user/user.json
    put:
      description: Edita un usuario especifico
      body:
        application/json:
          schema: !include schema/user/user.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/user/user.json
    delete:
      description: Elimina un usuario especifico
      responses:
        200:
          body:
            application/json:
              schema: !include schema/user/user.json

/v1/books:
  description: Servicios de creacion, edicion y eliminacion de libros
  post:
    description: Crea un nuevo libro
    body:
      application/json:
        schema: !include schema/books/model.post.json
    responses:
      200:
        body:
          application/json:
            schema: !include schema/books/model.json
  get:
    description: Recuperar todos los libros
    responses:
      200:
        body:
          application/json:
            schema: !include schema/books/model.array.json

  /{book_id}:
    get:
      description: Recupera un libro especifico
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.json
    put:
      description: Edita un libro especifico
      body:
        application/json:
          schema: !include schema/books/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.json
    delete:
      description: Elimina un libro especifico
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.json

  /page/{page}/limit/{limit}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.array.json

  /page/{page}/limit/{limit}/search:
    get:
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.array.json

  /size:
    get:
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.array.json

  /catalog/{id}/page/{page}/limit/{limit}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.array.json

/v1/thesis:
  description: Servicios de creacion, edicion y eliminacion de tesis
  post:
    description: Crea una nueva tesis
    body:
      application/json:
        schema: !include schema/thesis/model.post.json
    responses:
      200:
        body:
          application/json:
            schema: !include schema/thesis/model.json
  get:
    description: Recupera todas las tesis
    responses:
      200:
        body:
          application/json:
            schema: !include schema/thesis/model.array.json

  /{thesis_id}:
    get:
      description: Recupera una tesis especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.json
    put:
      description: Edita una tesis especifica
      body:
        application/json:
          schema: !include schema/thesis/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.json
    delete:
      description: Elimina una tesis especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.json

    /page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /page/{page}/limit/{limit}/search:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /size:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /catalog/{id}/page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

/v1/magazine:
  description: Servicios de creacion, edicion y eliminacion de revistas
  post:
    description: Crea una nueva revista
    body:
      application/json:
        schema: !include schema/magazine/model.post.json
    responses:
      200:
        body:
          application/json:
            schema: !include schema/magazine/model.json
  get:
    description: Recupera todas las revistas
    responses:
      200:
        body:
          application/json:
            schema: !include schema/magazine/model.array.json

  /{magazine_id}:
    get:
      description: Recupera una revista especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.json
    put:
      description: Edita una revista especifica
      body:
        application/json:
          schema: !include schema/magazine/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.json
    delete:
      description: Elimina una revista especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.json

    /page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /page/{page}/limit/{limit}/search:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /size:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /catalog/{id}/page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json


/v1/catalogs:
  /books:
    description: Servicios de creacion, edicion y eliminacion de libros
    post:
      description: Crea un nuevo libro
      body:
        application/json:
          schema: !include schema/books/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.json
    get:
      description: Recuperar todos los libros
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.array.json

  /{catalog_id}/books:
    get:
      description: Recupera un libro especifico
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.json
    put:
      description: Edita un libro especifico
      body:
        application/json:
          schema: !include schema/books/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.json
    delete:
      description: Elimina un libro especifico
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.json

  /{catalog_id}/books/page/{page}/limit/{limit}:
    get:
      description: Recupera libros paginados con um limite
      responses:
        200:
          body:
            application/json:
              schema: !include schema/books/model.array.json

  /thesis:
    description: Servicios de creacion, edicion y eliminacion de tesis
    post:
      description: Crea una nueva tesis
      body:
        application/json:
          schema: !include schema/thesis/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.json
    get:
      description: Recupera todas las tesis
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.array.json

  /{catalog_id}/thesis:
    get:
      description: Recupera una tesis especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.json
    put:
      description: Edita una tesis especifica
      body:
        application/json:
          schema: !include schema/thesis/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.json
    delete:
      description: Elimina una tesis especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/thesis/model.json

    /page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /page/{page}/limit/{limit}/search:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /size:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /catalog/{id}/page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

  /magazine:
    description: Servicios de creacion, edicion y eliminacion de revistas
    post:
      description: Crea una nueva revista
      body:
        application/json:
          schema: !include schema/magazine/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.json
    get:
      description: Recupera todas las revistas
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.array.json

  /{catalog_id}/magazine:
    get:
      description: Recupera una revista especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.json
    put:
      description: Edita una revista especifica
      body:
        application/json:
          schema: !include schema/magazine/model.post.json
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.json
    delete:
      description: Elimina una revista especifica
      responses:
        200:
          body:
            application/json:
              schema: !include schema/magazine/model.json

    /page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /page/{page}/limit/{limit}/search:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /size:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json

    /catalog/{id}/page/{page}/limit/{limit}:
      get:
        responses:
          200:
            body:
              application/json:
                schema: !include schema/books/model.array.json
