#%RAML 0.8
title: Lagash Integration
version: v1
baseUri: http://localhost:6040
mediaType: application/json

/api/v1/students/{student_id}:
  uriParameters:
     student_id:
       type: string
  get:
    description: Gets student information
    headers:
      x-api-key:
        description: Security access token
        example: abcdefghijabcdefghijabcdefghij
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "student_id" : "650000000",
                "first_name": "Loren Ipsum",
                "last_name": "sit amend",
                "image": "http://image/12345.jpg",
                "faculty": {
                  "faculty_id": 5,
                  "semester": 9
                }
              }
      500:
        body:
          application/json:
            example: |
              {
                "meesage": "No existe un estudiante con este ID",
                "examples": [
                  "Token invalido",
                  "No existe un estudiante con este ID",
                  "Tiene que proveer un ID de un estudiante"
                ]
              }

/api/v1/students/{student_id}/validate:
  get:
    description: Validates a student if its available to do any action
    headers:
      x-api-key:
        description: Security access token
        example: abcdefghijabcdefghijabcdefghij
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "is_valid" : true
              }
      500:
        body:
          application/json:
            example: |
              {
                "meesage": "El estudiante no esta autorizado para realizar esta accion",
                "examples": [
                  "Token invalido",
                  "No existe un estudiante con este ID",
                  "Tiene que proveer un ID de un estudiante",
                  "El estudiante no esta autorizado para realizar esta accion",
                  "El estudiante esta inactivo"
                ]
              }


/api/v1/faculties:
  get:
    description: Retrieves current faculties of university
    headers:
      x-api-key:
        description: Security access token
        example: abcdefghijabcdefghijabcdefghij
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "faculty_id": 1,
                  "name": "Ing. Sistemas"
                },
                {
                  "faculty_id": 2,
                  "name": "FCEA"
                },
                {
                  "faculty_id": 3,
                  "name": "Salud"
                }
              ]
      500:
        body:
          application/json:
            example: |
              {
                "meesage": "Token invalido",
                "examples": [
                  "Token invalido"
                ]
              }
